language: ruby

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7

gemfile:
  - gemfiles/rugged-0.24.gemfile
  - gemfiles/rugged-0.23.gemfile
  - gemfiles/rugged-0.22.gemfile

before_install: gem install bundler

services:
  - redis-server

sudo: false
